# Generated by Django 4.2.16 on 2024-10-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesectionmodel',
            name='image_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
