# Generated by Django 4.2.16 on 2024-10-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_homesectionmodel_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiolinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=20)),
                ('site_link', models.CharField(max_length=200)),
                ('icon_link', models.CharField(max_length=200)),
            ],
        ),
    ]
