# Generated by Django 4.2.16 on 2024-10-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_biolinkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mainpage/static/image')),
                ('image_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
