# Generated by Django 4.2.16 on 2024-10-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_portfoliomodel_framework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='framework',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
