# Generated by Django 4.2.16 on 2024-10-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_alter_portfoliomodel_framework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomodel',
            old_name='framework',
            new_name='software',
        ),
    ]
