# Generated by Django 4.2.16 on 2024-10-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_description', models.TextField()),
                ('portfolio_description', models.TextField()),
                ('contact_description', models.TextField()),
            ],
        ),
    ]
